title: Ivaylo Gochkov
author: Ivaylo Gochkov
url: http://blog.gochkov.com
github_username:  igochkov
twitter_username: igochkov
linkedin_username: ivaylogochkov
stackoverflow_user: '6793719'

timezone: Europe/Amsterdam
show_excerpts: false

minima:
  date_format: "%d %B %Y" # http://shopify.github.io/liquid/filters/date/

markdown: kramdown
