title: Ivaylo Gochkov
author: Ivaylo Gochkov
url: http://blog.gochkov.com
github_username:  igochkov
twitter_username: igochkov
linkedin_username: ivaylogochkov
stackoverflow_user: '6793719'
rss: rss

timezone: Europe/Amsterdam
show_excerpts: false

markdown: kramdown
theme: minima

minima:
  date_format: "%d %B %Y" # http://shopify.github.io/liquid/filters/date/

exclude:
  - Gemfile
  - Gemfile.lock