title: Ivaylo Gochkov - Blog
author: Ivaylo Gochkov
url: "http://blog.gochkov.com"

github_username:  igochkov
twitter_username: igochkov
linkedin_username: ivaylogochkov
stackoverflow_user: '6793719'
rss: rss

google_analytics: UA-114964508-1

timezone: Europe/Amsterdam
show_excerpts: false

markdown: kramdown
theme: minima

minima:
  date_format: "%d %B %Y"

disqus:
  shortname: igochkov

plugins:
  - jekyll-feed

header_pages:
  - about.md