title: Ivaylo Gochkov - Blog
author: Ivaylo Gochkov
url: "http://blog.gochkov.com"

github_username:  igochkov
twitter_username: igochkov
linkedin_username: ivaylogochkov
rss: rss

timezone: Europe/Amsterdam
permalink: /:title
markdown: kramdown
theme: minima
show_excerpts: false

minima:
  date_format: "%d %B %Y"

disqus:
  shortname: igochkov

plugins:
  - jekyll-feed

header_pages:
  - about.md
