title: My blog
author: Ivaylo Gochkov
description: > # this means to ignore newlines until "baseurl:"
  TODO: Description of my blog

# social links
github_username:  igochkov
linkedin_username: ivaylogochkov
twitter_username: igochkov

disqus:
    shortname: igochkov

google_analytics: UA-114964508-1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d %b %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - index.md

# Build settings
markdown: kramdown
theme: minima